#!/bin/bash
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;32m-        SSHPLUS BY VPSMAX VIP - PREMIUM Script       -\033[0m"
echo -e "\033[0;32m-              REQUESTED BY STAR_JANI & Biin Baadal Barsaat          -\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
echo -e "\033[1;31mRESTARTING...\033[0m"
shutdown -r now